

// Delivery
export const COLLECTION_DELIVERIES_FIELD_ID: string = 'id'
export const COLLECTION_DELIVERIES_FIELD_CREATION_DATE: string = 'creation_date'
export const COLLECTION_DELIVERIES_FIELD_STATE: string = 'state'
export const COLLECTION_DELIVERIES_FIELD_PICKUP: string = 'pickup'
export const COLLECTION_DELIVERIES_FIELD_DROPOFF: string = 'dropoff'
export const COLLECTION_DELIVERIES_FIELD_ZONE_ID: string = 'zone_id'


// HTTP return codes
export const HTTP_ANSWER_CODES_100_CONTINUE : number = 100
export const HTTP_ANSWER_CODES_101_SWITCHING_PROTOCOL : number = 101
export const HTTP_ANSWER_CODES_102_PROCESSING : number = 102
export const HTTP_ANSWER_CODES_103_EARLY_HINTS : number = 103

export const HTTP_ANSWER_CODES_200_OK : number = 200
export const HTTP_ANSWER_CODES_201_CREATED : number = 201
export const HTTP_ANSWER_CODES_202_ACCEPTED : number = 202
export const HTTP_ANSWER_CODES_203_NON_AUTHORITATIVE_INFORMATION : number = 203
export const HTTP_ANSWER_CODES_204_NO_CONTENT : number = 204
export const HTTP_ANSWER_CODES_205_RESET_CONTENT : number = 205
export const HTTP_ANSWER_CODES_206_PARTIAL_CONTENT : number = 206
export const HTTP_ANSWER_CODES_207_MULTI_STATUS : number = 207
export const HTTP_ANSWER_CODES_208_ALREADY_REPORTED : number = 208
export const HTTP_ANSWER_CODES_226_IM_USED : number = 226

export const HTTP_ANSWER_CODES_300_MULTIPLE_CHOICE : number = 300
export const HTTP_ANSWER_CODES_301_MOVED_PERMANENTLY : number = 301
export const HTTP_ANSWER_CODES_302_FOUND : number = 302
export const HTTP_ANSWER_CODES_303_SEE_OTHER : number = 303
export const HTTP_ANSWER_CODES_304_NOT_MODIFIED : number = 304
export const HTTP_ANSWER_CODES_305_USE_PROXY : number = 305
export const HTTP_ANSWER_CODES_306_UNUSED : number = 306
export const HTTP_ANSWER_CODES_307_TEMPORARY_REDIRECT : number = 307
export const HTTP_ANSWER_CODES_308_PERMANENT_REDIRECT : number = 308

export const HTTP_ANSWER_CODES_400_BAD_REQUEST : number = 400
export const HTTP_ANSWER_CODES_401_UNAUTHORIZED : number = 401
export const HTTP_ANSWER_CODES_402_PAYMENT_REQUIRED : number = 402
export const HTTP_ANSWER_CODES_403_FORBIDDEN : number = 403
export const HTTP_ANSWER_CODES_404_NOT_FOUND : number = 404
export const HTTP_ANSWER_CODES_405_METHOD_NOT_ALLOWED : number = 405
export const HTTP_ANSWER_CODES_406_NOT_ACCEPTABLE : number = 406
export const HTTP_ANSWER_CODES_407_PROXY_AUTHENTICATION_REQUIRED : number = 407
export const HTTP_ANSWER_CODES_408_REQUEST_TIMEOUT : number = 408
export const HTTP_ANSWER_CODES_409_CONFLICT : number = 409
export const HTTP_ANSWER_CODES_410_GONE : number = 410
export const HTTP_ANSWER_CODES_411_LENGTH_REQUIRED : number = 411
export const HTTP_ANSWER_CODES_412_PRECONDITION_FAILED : number = 412
export const HTTP_ANSWER_CODES_413_PAYLOAD_TOO_LARGE : number = 413
export const HTTP_ANSWER_CODES_414_URI_TOO_LONG : number = 414
export const HTTP_ANSWER_CODES_415_UNSUPORTED_MEDIA_TYPE : number = 415
export const HTTP_ANSWER_CODES_416_RANGE_NOT_SATISFIABLE : number = 416
export const HTTP_ANSWER_CODES_417_EXPECTATION_FAILED : number = 417
export const HTTP_ANSWER_CODES_418_IM_A_TEAPOT : number = 418
export const HTTP_ANSWER_CODES_421_MISDIRECTED_REQUEST : number = 421
export const HTTP_ANSWER_CODES_422_UNPROCESSABLE_ENTITY : number = 422
export const HTTP_ANSWER_CODES_423_LOCKED : number = 423
export const HTTP_ANSWER_CODES_424_FAILED_DEPENDENCY : number = 424
export const HTTP_ANSWER_CODES_425_TOO_EARLY : number = 425
export const HTTP_ANSWER_CODES_426_UPGRADE_REQUIRED : number = 426
export const HTTP_ANSWER_CODES_428_PRECONDITION_REQUIRED : number = 428
export const HTTP_ANSWER_CODES_429_TOO_MANY_REQUESTS : number = 429
export const HTTP_ANSWER_CODES_431_REQUEST_HEADER_FIELDS_TOO_LARGE : number = 431
export const HTTP_ANSWER_CODES_415_UNAVAILABLE_FOR_LEGAL_REASONS : number = 451

export const HTTP_ANSWER_CODES_500_INTERNAL_SERVER_ERROR : number = 500
export const HTTP_ANSWER_CODES_501_NOT_IMPLEMENTED : number = 501
export const HTTP_ANSWER_CODES_502_BAD_GATEWAY : number = 502
export const HTTP_ANSWER_CODES_503_SERVICE_UNAVAILABLE : number = 503
export const HTTP_ANSWER_CODES_504_GATEWAY_TIMEOUT : number = 504
export const HTTP_ANSWER_CODES_505_HTTP_VERSION_NOT_SUPPORTED : number = 505
export const HTTP_ANSWER_CODES_506_VARIANT_ALSO_NEGOTIATES : number = 506
export const HTTP_ANSWER_CODES_507_INSUFFICIENT_STORAGE : number = 507
export const HTTP_ANSWER_CODES_508_LOOP_DETECTED : number = 508
export const HTTP_ANSWER_CODES_510_NOT_EXTENDED : number = 510
export const HTTP_ANSWER_CODES_511_NETWORK_AUTHENTICATION_REQUIRED : number = 511
